# Generated by Django 3.1.7 on 2021-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgroup',
            name='members',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='newgroup',
            name='owner',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='newgroup',
            name='name',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
