# Generated by Django 3.1.7 on 2021-04-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210326_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='test',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='newuser',
            name='major',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
