# Generated by Django 3.1.7 on 2021-04-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210403_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='applied',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_in',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
