# Generated by Django 3.1.7 on 2021-04-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_newuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='likes',
            field=models.JSONField(null=True),
        ),
    ]
