# Generated by Django 3.1.7 on 2021-05-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_newuser_isteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
