# Generated by Django 3.1.7 on 2021-05-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210510_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='applied',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='likes',
            field=models.JSONField(default=[]),
        ),
    ]
