# Generated by Django 3.1.7 on 2021-05-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210515_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='applied',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='likes',
            field=models.JSONField(default=dict),
        ),
    ]
