# Generated by Django 3.1.7 on 2021-04-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
