# Generated by Django 3.1.7 on 2021-04-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20210413_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='test',
            field=models.JSONField(null=True),
        ),
    ]
