# Generated by Django 3.1.7 on 2021-04-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='applications',
            field=models.JSONField(null=True),
        ),
    ]
