# Generated by Django 3.1.7 on 2021-04-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_requests_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='userid',
            field=models.IntegerField(blank=True),
        ),
    ]
