# Generated by Django 3.1.7 on 2021-04-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_auto_20210417_0839'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('userid',)},
        ),
        migrations.RemoveField(
            model_name='requests',
            name='groupname',
        ),
    ]
