# Generated by Django 3.1.7 on 2021-04-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20210417_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='groupname',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='group.group'),
        ),
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('groupname', 'userid')},
        ),
    ]
