# Generated by Django 3.1.7 on 2021-04-17 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_auto_20210417_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='groupname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='group.group'),
        ),
    ]
