# Generated by Django 3.1.7 on 2021-04-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_auto_20210417_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('groupname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted', to='group.group')),
            ],
            options={
                'unique_together': {('groupname', 'userid')},
            },
        ),
    ]
