# Generated by Django 3.1.7 on 2021-04-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20210417_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='title',
            new_name='topic',
        ),
    ]
