# Generated by Django 3.1.7 on 2021-04-18 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0017_auto_20210418_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='person',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
    ]
