# Generated by Django 3.1.7 on 2021-04-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0018_requests_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='requests',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('groupname',)},
        ),
        migrations.RemoveField(
            model_name='requests',
            name='person',
        ),
    ]
