# Generated by Django 3.1.7 on 2021-04-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0019_auto_20210418_1200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('groupname', 'firstName')},
        ),
    ]
