# Generated by Django 3.1.7 on 2021-04-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0020_auto_20210418_1348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('groupname', 'userid')},
        ),
    ]
