# Generated by Django 3.1.7 on 2021-04-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0021_auto_20210418_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accepted',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='accepted',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
