# Generated by Django 3.1.7 on 2021-04-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0023_requests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(default='tbd', max_length=100),
        ),
    ]
