# Generated by Django 3.1.7 on 2021-04-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0024_auto_20210419_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='likes',
            field=models.JSONField(null=True),
        ),
    ]
