# Generated by Django 3.1.7 on 2021-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0025_group_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='confirmed',
            field=models.CharField(default='tbd', max_length=100),
        ),
    ]
