# Generated by Django 3.1.7 on 2021-05-03 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0028_proposals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='groupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='group.group'),
        ),
    ]
