# Generated by Django 3.1.7 on 2021-05-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0029_auto_20210503_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='proposal',
            field=models.CharField(default='tbd', max_length=50),
        ),
    ]
