# Generated by Django 3.1.7 on 2021-05-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0030_group_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals',
            name='feedback',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
