# Generated by Django 3.1.7 on 2021-05-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0031_proposals_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposals',
            old_name='status',
            new_name='progress',
        ),
    ]
