# Generated by Django 3.1.7 on 2021-05-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0032_auto_20210505_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposals',
            old_name='feedback',
            new_name='feedbacks',
        ),
    ]
