# Generated by Django 3.1.7 on 2021-05-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0033_auto_20210505_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposals',
            old_name='feedbacks',
            new_name='feedback',
        ),
    ]
