# Generated by Django 3.1.7 on 2021-05-06 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0035_auto_20210506_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='person',
            field=models.ForeignKey(default=72, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requests',
            name='userid',
            field=models.IntegerField(blank=True),
        ),
    ]
