# Generated by Django 3.1.7 on 2021-05-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0036_auto_20210506_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='recruitment',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
