# Generated by Django 3.1.7 on 2021-05-15 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0038_auto_20210515_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='person',
        ),
        migrations.AlterField(
            model_name='requests',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
    ]
