# Generated by Django 3.1.7 on 2021-05-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0040_auto_20210515_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='userid',
            field=models.IntegerField(blank=True),
        ),
    ]
