# Generated by Django 3.1.7 on 2021-05-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0041_auto_20210515_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='test',
        ),
        migrations.AddField(
            model_name='group',
            name='len',
            field=models.IntegerField(default=0),
        ),
    ]
