# Generated by Django 3.1.7 on 2021-05-31 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0043_auto_20210601_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='requests',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
