# Generated by Django 3.1.7 on 2021-05-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0045_auto_20210601_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='userid',
            field=models.IntegerField(blank=True),
        ),
    ]
