# Generated by Django 3.1.7 on 2021-05-31 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0046_auto_20210601_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='userids',
            field=models.ForeignKey(db_column='userids', default=44, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
