# Generated by Django 3.1.7 on 2021-04-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
