# Generated by Django 3.1.7 on 2021-04-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20210408_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
